apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: nodejs-messaging-work-queue-worker
      namespace: more-amqp
      labels:
        project: nodejs-messaging-work-queue-worker
        version: 1.0.0
        provider: nodeshift
        app: nodejs-messaging-work-queue-worker
      annotations:
        nodeshift/git-branch: make-it-rhoar
        nodeshift/git-commit: 057755a9fa6987fa98d7231966ff9709c2ada6ba
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: nodejs-messaging-work-queue-worker
        project: nodejs-messaging-work-queue-worker
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - nodejs-messaging-work-queue-worker
            from:
              kind: ImageStreamTag
              name: 'nodejs-messaging-work-queue-worker:latest'
      template:
        metadata:
          labels:
            project: nodejs-messaging-work-queue-worker
            version: 1.0.0
            provider: nodeshift
            app: nodejs-messaging-work-queue-worker
          annotations:
            nodeshift/git-branch: make-it-rhoar
            nodeshift/git-commit: 057755a9fa6987fa98d7231966ff9709c2ada6ba
        spec:
          containers:
            - readinessProbe:
                httpGet:
                  path: /api/health/readiness
                  scheme: HTTP
                  port: 8080
              livenessProbe:
                httpGet:
                  path: /api/health/liveness
                  scheme: HTTP
                  port: 8080
                initialDelaySeconds: 60
                periodSeconds: 30
              image: nodejs-messaging-work-queue-worker
              name: nodejs-messaging-work-queue-worker
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: messaging-service
              env: []
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: messaging-service
      namespace: more-amqp
      labels:
        project: nodejs-messaging-work-queue-worker
        version: 1.0.0
        provider: nodeshift
    data:
      MESSAGING_SERVICE_HOST: work-queue-broker-amq-amqp
      MESSAGING_SERVICE_PORT: '5672'
  - apiVersion: v1
    kind: Route
    spec:
      to:
        kind: Service
        name: nodejs-messaging-work-queue-worker
      port:
        targetPort: 8080
    metadata:
      name: nodejs-messaging-work-queue-worker
      namespace: more-amqp
      labels:
        project: nodejs-messaging-work-queue-worker
        version: 1.0.0
        provider: nodeshift
  - apiVersion: v1
    kind: Service
    spec:
      selector:
        project: nodejs-messaging-work-queue-worker
        provider: nodeshift
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
      type: ClusterIP
    metadata:
      name: nodejs-messaging-work-queue-worker
      namespace: more-amqp
      labels:
        project: nodejs-messaging-work-queue-worker
        version: 1.0.0
        provider: nodeshift
      annotations:
        nodeshift/git-branch: make-it-rhoar
        nodeshift/git-commit: 057755a9fa6987fa98d7231966ff9709c2ada6ba
