apiVersion: v1
kind: Template
metadata:
  name: nodejs-messaging-work-queue-worker
  annotations:
    iconClass: icon-jboss
    tags: nodejs, microservice, messaging
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: The Node.js Work Queue Mission demonstrates scalable task processing using messaging
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: https://github.com/ssorj/nodejs-messaging-work-queue
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: worker
    required: true
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook.
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nodejs-messaging-work-queue-worker
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'bucharestgold/centos7-s2i-nodejs:10.x'
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: nodejs-messaging-work-queue-worker
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-messaging-work-queue-worker:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime:latest
        incremental: true
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    type: ClusterIP
    selector:
      project: nodejs-messaging-work-queue-worker
      provider: nodeshift
  metadata:
    name: nodejs-messaging-work-queue-worker
    labels:
      provider: nodeshift
      expose: 'true'
      project: nodejs-messaging-work-queue-worker
      version: 2.0.0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: nodejs-messaging-work-queue-worker
    labels:
      app: nodejs-messaging-work-queue-worker
      provider: nodeshift
      project: nodejs-messaging-work-queue-worker
      version: 2.0.0
  spec:
    template:
      spec:
        containers:
          - envFrom:
              - configMapRef:
                  name: messaging-service
            readinessProbe:
              httpGet:
                path: /api/health/readiness
                port: 8080
                scheme: HTTP
            livenessProbe:
              httpGet:
                path: /api/health/liveness
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 30
            image: nodejs-messaging-work-queue-worker
            name: nodejs-messaging-work-queue-worker
            securityContext:
              privileged: false
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
      metadata:
        labels:
          app: nodejs-messaging-work-queue-worker
          project: nodejs-messaging-work-queue-worker
          provider: nodeshift
          version: 2.0.0
    replicas: 1
    selector:
      app: nodejs-messaging-work-queue-worker
      project: nodejs-messaging-work-queue-worker
      provider: nodeshift
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - nodejs-messaging-work-queue-worker
          from:
            kind: ImageStreamTag
            name: 'nodejs-messaging-work-queue-worker:latest'
